excluded:
 - Pods
 - Carthage
 - vendor/bundle
 - fastlane

disabled_rules:
 - trailing_whitespace
 - colon
 
line_length: 300
cyclomatic_complexity:
  warning: 20
  error: 50
function_body_length:
  warning: 100
  error: 500
type_body_length:
  warning: 300
  error: 500
