language: objective-c
os: osx
osx_image: xcode11.6
cache:
  - cocoapods
  - bundler
 
before_install:
  - gem install bundler --version '2.1.4'
  - bundle install --path vendor/bundle

script:
  - bundle exec pod install --repo-update
  - bundle exec fastlane tests
  - if [ "$TRAVIS_BRANCH" = "release" ]; then bundle exec fastlane deploy_app; fi

notifications:
  slack:
    secure: $SLACK_TOKEN