language: objective-c
os: osx
osx_image: xcode11.6
cache:
  - cocoapods
  - bundler
 
addons:
- ssh_known_hosts: github.com
 
before_install:
  - gem install bundler --version '2.1.4'
  - bundle install --path vendor/bundle
  - openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out ./deploy_key -d
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key

script:
  - bundle exec pod install --repo-update
  - bundle exec fastlane tests
  - if [ "$TRAVIS_BRANCH" = "release" ]; then bundle exec fastlane deploy_app; fi

notifications:
  slack:
    secure: $SLACK_TOKEN